#!/usr/bin/env node
// G02: generate every key the gov <-> citizen bridge needs (Bible section 8). Safe to re-run:
// existing values are kept unless you pass --force. Secrets are written to the .env files and
// never printed.
//
//   gov .env      : gov JWT pair, sync PUBLIC key, write-back PRIVATE key, phone-seal PRIVATE key, admin password
//   citizen .env  : sync PRIVATE key, write-back PUBLIC key, phone-seal PUBLIC key, bridge URLs
//
// Key format: base64 of DER (PKCS8 for private keys, SPKI for public keys), one line each.
import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const force = process.argv.includes('--force');
const here = dirname(fileURLToPath(import.meta.url));
const govDir = resolve(here, '..');
const citizenDir = resolve(govDir, '..', 'NyaySetu_Full_v2');

const pair = (type) => {
  const { privateKey, publicKey } = generateKeyPairSync(type);
  return {
    priv: privateKey.export({ type: 'pkcs8', format: 'der' }).toString('base64'),
    pub: publicKey.export({ type: 'spki', format: 'der' }).toString('base64'),
  };
};
const secret = (n = 24) => randomBytes(n).toString('base64url');

function readEnv(file) {
  const out = {};
  if (!existsSync(file)) return out;
  for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}
function upsertEnv(file, values, header) {
  const text = existsSync(file) ? readFileSync(file, 'utf8') : '';
  const lines = text.split(/\r?\n/);
  const seen = new Set();
  const next = lines.map((line) => {
    const m = line.match(/^([A-Z0-9_]+)=/);
    if (m && m[1] in values) { seen.add(m[1]); return `${m[1]}=${values[m[1]]}`; }
    return line;
  });
  const add = Object.keys(values).filter((k) => !seen.has(k));
  let body = next.join('\n').replace(/\n+$/, '');
  if (add.length) body += `\n${header ? `\n# ${header}\n` : ''}${add.map((k) => `${k}=${values[k]}`).join('\n')}`;
  writeFileSync(file, body + '\n');
}

const govEnvFile = join(govDir, '.env');
const citEnvFile = join(citizenDir, '.env');
const gov = readEnv(govEnvFile);
const cit = readEnv(citEnvFile);
const have = (o, ...keys) => keys.every((k) => o[k]);

const needGov = force || !have(gov, 'GOV_JWT_PRIVATE_KEY', 'GOV_JWT_PUBLIC_KEY', 'SYNC_SIGNING_PUBLIC_KEY', 'GOV_WRITEBACK_PRIVATE_KEY', 'GOV_PHONE_SEAL_PRIVATE_KEY', 'GOV_PHONE_SEAL_PUBLIC_KEY');
const needCit = force || !have(cit, 'SYNC_SIGNING_PRIVATE_KEY', 'GOV_WRITEBACK_PUBLIC_KEY', 'GOV_PHONE_SEAL_PUBLIC_KEY');

let govVals = {};
let citVals = {};
if (needGov || needCit) {
  // The two sides must agree, so when either is missing both are regenerated together.
  const jwt = pair('ed25519');
  const sync = pair('ed25519');
  const wb = pair('ed25519');
  const seal = pair('x25519');
  govVals = {
    GOV_JWT_PRIVATE_KEY: jwt.priv,
    GOV_JWT_PUBLIC_KEY: jwt.pub,
    SYNC_SIGNING_PUBLIC_KEY: sync.pub,
    GOV_WRITEBACK_PRIVATE_KEY: wb.priv,
    GOV_PHONE_SEAL_PRIVATE_KEY: seal.priv,
    GOV_PHONE_SEAL_PUBLIC_KEY: seal.pub,
  };
  citVals = {
    SYNC_SIGNING_PRIVATE_KEY: sync.priv,
    GOV_WRITEBACK_PUBLIC_KEY: wb.pub,
    GOV_PHONE_SEAL_PUBLIC_KEY: seal.pub,
  };
}
// Non-key settings: only fill what is missing.
const dbPass = gov.GOV_DB_PASSWORD || secret(18);
const appPass = gov.GOV_APP_DB_PASSWORD || secret(18);
Object.assign(govVals, {
  GOV_DB_PASSWORD: dbPass,
  GOV_APP_DB_PASSWORD: appPass,
  DATABASE_URL: gov.DATABASE_URL || `postgres://postgres:${dbPass}@localhost:5433/nyaysetu_gov`,
  PORT: gov.PORT || '8081',
  SYNC_PORT: gov.SYNC_PORT || '8091',
  GOV_WEB_ORIGIN: gov.GOV_WEB_ORIGIN || 'http://localhost:5174',
  CITIZEN_INTERNAL_URL: gov.CITIZEN_INTERNAL_URL || 'http://localhost:8090',
  GOV_ADMIN_PASSWORD: gov.GOV_ADMIN_PASSWORD || secret(12),
});
Object.assign(citVals, {
  GOV_SYNC_URL: cit.GOV_SYNC_URL || 'http://localhost:8091',
  GOV_BRIDGE_PORT: cit.GOV_BRIDGE_PORT || '8090',
});

upsertEnv(govEnvFile, govVals, 'NyaySetu Gov (generated by scripts/gen-keys.mjs; never commit)');
if (existsSync(citizenDir)) {
  upsertEnv(citEnvFile, citVals, 'Gov bridge (generated by NyaySetu_Gov/scripts/gen-keys.mjs; never commit)');
}

console.log(needGov || needCit ? 'Generated a fresh key set.' : 'Keys already present: kept as they are (use --force to regenerate).');
console.log(`Gov env:     ${govEnvFile}`);
console.log(existsSync(citizenDir) ? `Citizen env: ${citEnvFile}` : `Citizen folder not found (${citizenDir}); run again after it exists.`);
console.log('Demo admin login: admin@nyaysetu.local, password = GOV_ADMIN_PASSWORD in the gov .env');
